"""
Seed community marketplace bases.

Creates ~63 community project bases from well-known open-source repos across
32 framework categories. All bases are linked to a shared "Open Source Community"
account.

Can be run standalone or called from the startup seeder.
"""

import logging
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..models import MarketplaceBase, User

logger = logging.getLogger(__name__)

COMMUNITY_ACCOUNT = {
    "email": "community@tesslate.com",
    "username": "community",
    "slug": "community",
    "display_name": "Open Source Community",
}

COMMUNITY_BASES = [
    # ── Next.js ──────────────────────────────────────────────
    {
        "name": "Next.js Boilerplate",
        "slug": "nextjs-boilerplate",
        "description": "Production-ready Next.js boilerplate with App Router, Tailwind CSS, and TypeScript. 9.3k+ stars on GitHub.",
        "long_description": "A developer-friendly Next.js boilerplate featuring App Router, TypeScript, ESLint, Prettier, Husky, Lint-Staged, Jest, Testing Library, Commitlint, VSCode config, PostCSS, and Tailwind CSS. Built for performance and developer experience.",
        "git_repo_url": "https://github.com/ixartz/Next-js-Boilerplate.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\u25b2",
        "tags": ["nextjs", "react", "typescript", "tailwind", "boilerplate", "app-router"],
        "pricing_type": "free",
        "price": 0,
        "features": ["App Router", "TypeScript", "Tailwind CSS", "ESLint", "Jest", "Husky"],
        "tech_stack": ["Next.js", "React", "TypeScript", "Tailwind CSS"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "next-forge",
        "slug": "next-forge",
        "description": "Production-grade Turborepo template for Next.js apps. 4.5k+ stars on GitHub.",
        "long_description": "A comprehensive monorepo boilerplate for Next.js projects using Turborepo. Includes authentication, database ORM, email, analytics, and more — all pre-configured and ready for production deployment.",
        "git_repo_url": "https://github.com/haydenbleasel/next-forge.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\u25b2",
        "tags": ["nextjs", "turborepo", "monorepo", "typescript", "production"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Turborepo", "Authentication", "Database ORM", "Email", "Analytics"],
        "tech_stack": ["Next.js", "Turborepo", "TypeScript", "Prisma"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    # ── React (Vite) ─────────────────────────────────────────
    {
        "name": "Bulletproof React",
        "slug": "bulletproof-react",
        "description": "Scalable React architecture with best practices. 29.3k+ stars on GitHub.",
        "long_description": "A simple, scalable, and powerful architecture for building production-ready React applications. Features a well-organized project structure, testing setup, state management patterns, and API layer abstractions.",
        "git_repo_url": "https://github.com/alan2207/bulletproof-react.git",
        "default_branch": "master",
        "category": "frontend",
        "icon": "\u269b",
        "tags": ["react", "architecture", "best-practices", "scalable", "typescript"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Scalable Architecture", "Testing Setup", "State Management", "API Layer"],
        "tech_stack": ["React", "TypeScript", "Vite", "React Query"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "React Starter Kit",
        "slug": "react-starter-kit",
        "description": "Front-end starter kit using React, Relay, and Vite. 22.6k+ stars on GitHub.",
        "long_description": "An opinionated React starter kit with Vite, Relay, Material UI, and authentication. Designed for web application projects with a focus on developer experience and modern tooling.",
        "git_repo_url": "https://github.com/kriasoft/react-starter-kit.git",
        "default_branch": "main",
        "category": "frontend",
        "icon": "\u269b",
        "tags": ["react", "vite", "relay", "material-ui", "starter"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Vite Build", "Relay", "Material UI", "Authentication"],
        "tech_stack": ["React", "Vite", "Relay", "Material UI"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── FastAPI ───────────────────────────────────────────────
    {
        "name": "FastAPI Full Stack",
        "slug": "fastapi-fullstack",
        "description": "Official FastAPI full-stack template with React frontend. 27.8k+ stars on GitHub.",
        "long_description": "The official full-stack FastAPI template with a React frontend, SQLModel ORM, PostgreSQL database, Docker Compose for development and production, JWT authentication, email-based password recovery, and CI/CD with GitHub Actions.",
        "git_repo_url": "https://github.com/fastapi/full-stack-fastapi-template.git",
        "default_branch": "master",
        "category": "fullstack",
        "icon": "\U0001f680",
        "tags": ["fastapi", "react", "python", "postgresql", "docker", "fullstack"],
        "pricing_type": "free",
        "price": 0,
        "features": ["JWT Auth", "PostgreSQL", "Docker Compose", "CI/CD", "Email Recovery"],
        "tech_stack": ["FastAPI", "React", "SQLModel", "PostgreSQL", "Docker"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "FastAPI Boilerplate",
        "slug": "fastapi-boilerplate",
        "description": "Production-ready FastAPI boilerplate with async SQLAlchemy. 900+ stars on GitHub.",
        "long_description": "A scalable FastAPI boilerplate with async SQLAlchemy, Alembic migrations, JWT authentication, and a clean project structure. Follows best practices for building production-ready Python APIs.",
        "git_repo_url": "https://github.com/teamhide/fastapi-boilerplate.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f680",
        "tags": ["fastapi", "python", "async", "sqlalchemy", "boilerplate"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Async SQLAlchemy", "Alembic Migrations", "JWT Auth", "Clean Architecture"],
        "tech_stack": ["FastAPI", "Python", "SQLAlchemy", "Alembic"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Go ────────────────────────────────────────────────────
    {
        "name": "Go Project Layout",
        "slug": "go-project-layout",
        "description": "Standard Go project layout and conventions. 50.5k+ stars on GitHub.",
        "long_description": "The unofficial but widely-adopted set of common Go project layout patterns. Not an official Go standard but a set of historical and emerging project layout patterns in the Go ecosystem.",
        "git_repo_url": "https://github.com/golang-standards/project-layout.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f537",
        "tags": ["go", "golang", "project-layout", "standards", "best-practices"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Standard Layout", "Best Practices", "Documentation", "Examples"],
        "tech_stack": ["Go"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Go Clean Template",
        "slug": "go-clean-template",
        "description": "Clean Architecture template for Go services. 6.4k+ stars on GitHub.",
        "long_description": "A Go template implementing Clean Architecture principles with Gin web framework, GORM, and structured logging. Features dependency injection, database migrations, and comprehensive error handling.",
        "git_repo_url": "https://github.com/evrone/go-clean-template.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f537",
        "tags": ["go", "golang", "clean-architecture", "gin", "gorm"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Clean Architecture", "Gin Framework", "GORM", "Dependency Injection"],
        "tech_stack": ["Go", "Gin", "GORM", "PostgreSQL"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Go Clean Architecture",
        "slug": "go-clean-architecture",
        "description": "Go backend clean architecture with Gin and MongoDB. 4.5k+ stars on GitHub.",
        "long_description": "A production-ready Go backend implementing Uncle Bob's Clean Architecture with the Gin web framework. Includes JWT authentication, MongoDB integration, and a well-structured project layout.",
        "git_repo_url": "https://github.com/amitshekhariitbhu/go-backend-clean-architecture.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f537",
        "tags": ["go", "golang", "clean-architecture", "gin", "mongodb"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Clean Architecture", "JWT Auth", "MongoDB", "Gin Framework"],
        "tech_stack": ["Go", "Gin", "MongoDB"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Express ───────────────────────────────────────────────
    {
        "name": "Hackathon Starter",
        "slug": "hackathon-starter",
        "description": "Full-stack boilerplate for Node.js web apps. 34.9k+ stars on GitHub.",
        "long_description": "A boilerplate for Node.js web applications featuring Express, MongoDB, OAuth authentication (20+ providers), Bootstrap, and account management. Perfect for hackathons and rapid prototyping.",
        "git_repo_url": "https://github.com/sahat/hackathon-starter.git",
        "default_branch": "master",
        "category": "fullstack",
        "icon": "\U0001f3c6",
        "tags": ["express", "nodejs", "mongodb", "oauth", "hackathon", "fullstack"],
        "pricing_type": "free",
        "price": 0,
        "features": ["OAuth 2.0", "MongoDB", "Account Management", "Email", "Bootstrap"],
        "tech_stack": ["Express", "Node.js", "MongoDB", "Bootstrap"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Node Express Boilerplate",
        "slug": "node-express-boilerplate",
        "description": "Production-ready Node.js Express REST API boilerplate. 7.1k+ stars on GitHub.",
        "long_description": "A comprehensive boilerplate for building production-ready RESTful APIs using Node.js, Express, and MongoDB. Features JWT authentication, request validation, unit and integration tests, Docker support, and API documentation.",
        "git_repo_url": "https://github.com/hagopj13/node-express-boilerplate.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "E",
        "tags": ["express", "nodejs", "rest-api", "mongodb", "jwt", "boilerplate"],
        "pricing_type": "free",
        "price": 0,
        "features": ["JWT Auth", "Validation", "Testing", "Docker", "API Docs"],
        "tech_stack": ["Express", "Node.js", "MongoDB", "Jest"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Django ────────────────────────────────────────────────
    {
        "name": "Cookiecutter Django",
        "slug": "cookiecutter-django",
        "description": "Production-ready Django project template. 12.5k+ stars on GitHub.",
        "long_description": "The gold standard for Django project templates. Features Docker support, PostgreSQL, Celery, Mailpit, Sentry integration, and comprehensive settings management for development and production environments.",
        "git_repo_url": "https://github.com/cookiecutter/cookiecutter-django.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f40d",
        "tags": ["django", "python", "cookiecutter", "docker", "celery", "postgresql"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Docker", "Celery", "PostgreSQL", "Sentry", "Mailpit", "Production-Ready"],
        "tech_stack": ["Django", "Python", "PostgreSQL", "Celery", "Docker"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "wemake Django Template",
        "slug": "wemake-django-template",
        "description": "Bleeding-edge Django template with strict linting. 2k+ stars on GitHub.",
        "long_description": "An opinionated Django template with the strictest linting and code quality tools. Features wemake-python-styleguide, mypy, pytest, Docker, and a comprehensive CI/CD setup.",
        "git_repo_url": "https://github.com/wemake-services/wemake-django-template.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f40d",
        "tags": ["django", "python", "linting", "strict", "docker"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Strict Linting", "mypy", "pytest", "Docker", "CI/CD"],
        "tech_stack": ["Django", "Python", "Docker"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Laravel ───────────────────────────────────────────────
    {
        "name": "Laravel Starter Kit",
        "slug": "laravel-starter-kit",
        "description": "Official Laravel starter kit with Inertia and React/Vue. 800+ stars on GitHub.",
        "long_description": "The official Laravel starter kit providing authentication scaffolding with Inertia.js, supporting both React and Vue frontends. Includes Tailwind CSS, TypeScript, and a modern development experience.",
        "git_repo_url": "https://github.com/laravel/react-starter-kit.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f525",
        "tags": ["laravel", "php", "inertia", "react", "vue", "tailwind"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Authentication", "Inertia.js", "Tailwind CSS", "TypeScript"],
        "tech_stack": ["Laravel", "PHP", "Inertia.js", "React", "Tailwind CSS"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Laravel Boilerplate",
        "slug": "laravel-boilerplate",
        "description": "Full-featured Laravel boilerplate with admin panel. 5.7k+ stars on GitHub.",
        "long_description": "A comprehensive Laravel boilerplate featuring role-based access control, admin panel, social authentication, two-factor auth, and a clean, maintainable codebase following Laravel best practices.",
        "git_repo_url": "https://github.com/rappasoft/laravel-boilerplate.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f525",
        "tags": ["laravel", "php", "admin", "rbac", "social-auth"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Admin Panel", "RBAC", "Social Auth", "Two-Factor Auth"],
        "tech_stack": ["Laravel", "PHP", "Bootstrap"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Spring Boot ───────────────────────────────────────────
    {
        "name": "JHipster",
        "slug": "jhipster",
        "description": "Full-stack platform for generating Spring Boot + Angular/React/Vue apps. 21.8k+ stars on GitHub.",
        "long_description": "JHipster is a development platform to quickly generate, develop, and deploy modern web applications and microservice architectures. Supports Spring Boot, Angular, React, Vue, and multiple database options.",
        "git_repo_url": "https://github.com/jhipster/generator-jhipster.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f343",
        "tags": ["spring-boot", "java", "angular", "react", "microservices", "jhipster"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Code Generation", "Microservices", "JWT Auth", "Multiple Frontends"],
        "tech_stack": ["Spring Boot", "Java", "Angular", "React", "Vue"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Spring Boot Boilerplate",
        "slug": "spring-boot-boilerplate",
        "description": "Clean Spring Boot starter with JWT, PostgreSQL, and Docker. 400+ stars on GitHub.",
        "long_description": "A clean Spring Boot boilerplate project with JWT authentication, PostgreSQL database, Docker support, and a well-organized project structure following Spring best practices.",
        "git_repo_url": "https://github.com/Genc/spring-boot-boilerplate.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f343",
        "tags": ["spring-boot", "java", "jwt", "postgresql", "docker"],
        "pricing_type": "free",
        "price": 0,
        "features": ["JWT Auth", "PostgreSQL", "Docker", "Clean Architecture"],
        "tech_stack": ["Spring Boot", "Java", "PostgreSQL", "Docker"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Rails ─────────────────────────────────────────────────
    {
        "name": "Bullet Train",
        "slug": "bullet-train",
        "description": "SaaS framework built on Ruby on Rails. 1.7k+ stars on GitHub.",
        "long_description": "Bullet Train is the Ruby on Rails SaaS framework. Includes teams, invitations, roles, OAuth, payments with Stripe, beautiful Tailwind CSS templates, and a full developer experience out of the box.",
        "git_repo_url": "https://github.com/bullet-train-co/bullet_train.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f68a",
        "tags": ["rails", "ruby", "saas", "stripe", "tailwind", "teams"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Teams", "OAuth", "Stripe Payments", "Tailwind CSS", "Roles"],
        "tech_stack": ["Ruby on Rails", "Ruby", "Tailwind CSS", "Stripe"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Nextgen Rails",
        "slug": "nextgen-rails",
        "description": "Interactive Rails app generator with modern defaults. 400+ stars on GitHub.",
        "long_description": "An interactive generator for creating modern Ruby on Rails applications with sensible defaults. Pick and choose from a curated set of gems, configurations, and best practices.",
        "git_repo_url": "https://github.com/mattbrictson/nextgen.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f68a",
        "tags": ["rails", "ruby", "generator", "modern", "best-practices"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Interactive Generator", "Modern Defaults", "Curated Gems"],
        "tech_stack": ["Ruby on Rails", "Ruby"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Flutter ───────────────────────────────────────────────
    {
        "name": "Very Good CLI",
        "slug": "very-good-cli",
        "description": "Dart CLI for generating scalable Flutter/Dart projects. 2.2k+ stars on GitHub.",
        "long_description": "A Dart CLI by Very Good Ventures for generating opinionated, scalable Flutter and Dart projects. Features bloc architecture, comprehensive testing setup, and CI/CD configurations.",
        "git_repo_url": "https://github.com/VeryGoodOpenSource/very_good_cli.git",
        "default_branch": "main",
        "category": "mobile",
        "icon": "\U0001f4f1",
        "tags": ["flutter", "dart", "cli", "bloc", "mobile", "scalable"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Bloc Architecture", "Testing Setup", "CI/CD", "Code Generation"],
        "tech_stack": ["Flutter", "Dart", "Bloc"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Flutter Boilerplate",
        "slug": "flutter-boilerplate",
        "description": "Flutter boilerplate with clean architecture and state management. 1.6k+ stars on GitHub.",
        "long_description": "A comprehensive Flutter boilerplate project featuring clean architecture, MobX state management, dependency injection, networking with Dio, and a well-organized project structure.",
        "git_repo_url": "https://github.com/zubairehman/flutter-boilerplate-project.git",
        "default_branch": "master",
        "category": "mobile",
        "icon": "\U0001f4f1",
        "tags": ["flutter", "dart", "clean-architecture", "mobx", "mobile"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Clean Architecture", "MobX", "Dependency Injection", "Dio Networking"],
        "tech_stack": ["Flutter", "Dart", "MobX"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Expo / React Native ───────────────────────────────────
    {
        "name": "Ignite",
        "slug": "ignite",
        "description": "Battle-tested React Native boilerplate by Infinite Red. 17.6k+ stars on GitHub.",
        "long_description": "The battle-proven React Native boilerplate from Infinite Red. Features MobX-State-Tree, React Navigation, TypeScript, and a collection of pre-built components and utilities for rapid mobile development.",
        "git_repo_url": "https://github.com/infinitered/ignite.git",
        "default_branch": "master",
        "category": "mobile",
        "icon": "\U0001f525",
        "tags": ["react-native", "expo", "typescript", "mobx", "mobile", "boilerplate"],
        "pricing_type": "free",
        "price": 0,
        "features": ["MobX-State-Tree", "React Navigation", "TypeScript", "Pre-built Components"],
        "tech_stack": ["React Native", "Expo", "TypeScript", "MobX-State-Tree"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "RN Template Obytes",
        "slug": "rn-template-obytes",
        "description": "Production-ready React Native template with Expo. 2.1k+ stars on GitHub.",
        "long_description": "A production-ready React Native template using Expo with TypeScript, React Navigation, React Query, Zustand, i18n, and comprehensive testing setup. Follows Obytes' best practices for mobile development.",
        "git_repo_url": "https://github.com/obytes/react-native-template-obytes.git",
        "default_branch": "master",
        "category": "mobile",
        "icon": "\U0001f4f1",
        "tags": ["react-native", "expo", "typescript", "zustand", "i18n", "template"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Expo", "React Query", "Zustand", "i18n", "Testing Setup"],
        "tech_stack": ["React Native", "Expo", "TypeScript", "Zustand"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Vue / Nuxt ────────────────────────────────────────────
    {
        "name": "Vitesse",
        "slug": "vitesse",
        "description": "Opinionated Vite + Vue starter template by Anthony Fu. 8.9k+ stars on GitHub.",
        "long_description": "An opinionated Vite starter template with Vue 3, file-based routing, auto-imports, UnoCSS, Pinia state management, and i18n. Created and maintained by Anthony Fu with a focus on developer experience.",
        "git_repo_url": "https://github.com/antfu-collective/vitesse.git",
        "default_branch": "main",
        "category": "frontend",
        "icon": "\U0001f33f",
        "tags": ["vue", "vite", "typescript", "unocss", "pinia", "auto-imports"],
        "pricing_type": "free",
        "price": 0,
        "features": ["File-based Routing", "Auto Imports", "UnoCSS", "Pinia", "i18n"],
        "tech_stack": ["Vue 3", "Vite", "TypeScript", "UnoCSS", "Pinia"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Vitesse Nuxt 3",
        "slug": "vitesse-nuxt3",
        "description": "Vitesse experience for Nuxt 3 with auto-imports and UnoCSS. 1.8k+ stars on GitHub.",
        "long_description": "Bringing the Vitesse developer experience to Nuxt 3. Includes auto-imports, UnoCSS, Pinia state management, Vue Macros, and pre-configured development tools.",
        "git_repo_url": "https://github.com/antfu-collective/vitesse-nuxt3.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f33f",
        "tags": ["nuxt", "vue", "nuxt3", "typescript", "unocss", "auto-imports"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Nuxt 3", "Auto Imports", "UnoCSS", "Pinia", "Vue Macros"],
        "tech_stack": ["Nuxt 3", "Vue 3", "TypeScript", "UnoCSS"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Vuesion",
        "slug": "vuesion",
        "description": "Boilerplate for production-ready Vue.js Progressive Web Apps. 2.8k+ stars on GitHub.",
        "long_description": "The most complete boilerplate for production-ready Progressive Web Applications with Vue.js. Features Vuex, Vue Router, server-side rendering, internationalization, and comprehensive testing.",
        "git_repo_url": "https://github.com/vuesion/vuesion.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f33f",
        "tags": ["vue", "pwa", "ssr", "vuex", "i18n", "fullstack"],
        "pricing_type": "free",
        "price": 0,
        "features": ["PWA", "SSR", "Vuex", "i18n", "Testing"],
        "tech_stack": ["Vue", "Vuex", "Vue Router"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── SvelteKit ─────────────────────────────────────────────
    {
        "name": "SvelteKit SaaS Starter",
        "slug": "sveltekit-saas",
        "description": "Open-source SaaS template with SvelteKit and Stripe. 1.3k+ stars on GitHub.",
        "long_description": "A complete SaaS starter template built with SvelteKit, featuring Stripe integration, authentication, landing pages, and a dashboard. Everything needed to launch a subscription-based product.",
        "git_repo_url": "https://github.com/CriticalMoments/CMSaasStarter.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f525",
        "tags": ["sveltekit", "svelte", "saas", "stripe", "auth", "typescript"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Stripe Payments", "Authentication", "Landing Page", "Dashboard"],
        "tech_stack": ["SvelteKit", "Svelte", "Stripe", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "SvelteKit SaaS Starter (Startino)",
        "slug": "sveltekit-starter",
        "description": "Open-source SvelteKit SaaS starter with Supabase and Stripe. 300+ stars on GitHub.",
        "long_description": "A SaaS starter template combining SvelteKit with Supabase authentication and Stripe payments. Includes a landing page, dashboard, user management, and subscription billing.",
        "git_repo_url": "https://github.com/startino/saas-starter.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f525",
        "tags": ["sveltekit", "svelte", "saas", "supabase", "stripe"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Supabase Auth", "Stripe Payments", "Landing Page", "Dashboard"],
        "tech_stack": ["SvelteKit", "Svelte", "Supabase", "Stripe"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── NestJS ────────────────────────────────────────────────
    {
        "name": "NestJS Boilerplate",
        "slug": "nestjs-boilerplate",
        "description": "Scalable NestJS API boilerplate with auth, DB, and Docker. 2.8k+ stars on GitHub.",
        "long_description": "A production-ready NestJS boilerplate featuring JWT authentication, TypeORM, PostgreSQL, role-based access control, Swagger documentation, Docker, and CI/CD. Built for scalable enterprise applications.",
        "git_repo_url": "https://github.com/brocoders/nestjs-boilerplate.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f431",
        "tags": ["nestjs", "nodejs", "typescript", "typeorm", "postgresql", "docker"],
        "pricing_type": "free",
        "price": 0,
        "features": ["JWT Auth", "TypeORM", "RBAC", "Swagger", "Docker", "CI/CD"],
        "tech_stack": ["NestJS", "TypeScript", "TypeORM", "PostgreSQL", "Docker"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Awesome NestJS Boilerplate",
        "slug": "awesome-nest",
        "description": "NestJS boilerplate with GraphQL, Microservices, and CQRS. 1k+ stars on GitHub.",
        "long_description": "An awesome NestJS boilerplate featuring GraphQL, Microservices architecture, CQRS pattern, JWT authentication, and comprehensive documentation. Designed for complex enterprise applications.",
        "git_repo_url": "https://github.com/NarHakobyan/awesome-nest-boilerplate.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f431",
        "tags": ["nestjs", "nodejs", "graphql", "microservices", "cqrs"],
        "pricing_type": "free",
        "price": 0,
        "features": ["GraphQL", "Microservices", "CQRS", "JWT Auth"],
        "tech_stack": ["NestJS", "TypeScript", "GraphQL"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── T3 Stack ──────────────────────────────────────────────
    {
        "name": "create-t3-app",
        "slug": "create-t3-app",
        "description": "Best way to start a full-stack, typesafe Next.js app. 26.3k+ stars on GitHub.",
        "long_description": "The best way to start a full-stack, typesafe Next.js app. Features tRPC for end-to-end type safety, Prisma ORM, NextAuth.js for authentication, and Tailwind CSS for styling.",
        "git_repo_url": "https://github.com/t3-oss/create-t3-app.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f680",
        "tags": ["t3-stack", "nextjs", "trpc", "prisma", "nextauth", "tailwind"],
        "pricing_type": "free",
        "price": 0,
        "features": ["tRPC", "Prisma", "NextAuth.js", "Tailwind CSS", "Type Safety"],
        "tech_stack": ["Next.js", "tRPC", "Prisma", "NextAuth.js", "Tailwind CSS"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "create-t3-turbo",
        "slug": "create-t3-turbo",
        "description": "T3 Stack + Turborepo monorepo with Expo and Next.js. 5k+ stars on GitHub.",
        "long_description": "A clean and typesafe starter repo combining the T3 Stack with Turborepo. Includes both Next.js and Expo (React Native) apps sharing a common API layer via tRPC.",
        "git_repo_url": "https://github.com/t3-oss/create-t3-turbo.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f680",
        "tags": ["t3-stack", "turborepo", "nextjs", "expo", "trpc", "monorepo"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Turborepo", "Next.js + Expo", "tRPC", "Shared API Layer"],
        "tech_stack": ["Next.js", "Expo", "Turborepo", "tRPC", "Prisma"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Hono ──────────────────────────────────────────────────
    {
        "name": "Hono OpenAPI Starter",
        "slug": "hono-open-api-starter",
        "description": "Hono API starter with OpenAPI documentation. 600+ stars on GitHub.",
        "long_description": "A starter template for building type-safe APIs with Hono and automatic OpenAPI documentation generation. Features Zod validation, structured error handling, and a clean project structure.",
        "git_repo_url": "https://github.com/w3cj/hono-open-api-starter.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f525",
        "tags": ["hono", "openapi", "typescript", "zod", "api"],
        "pricing_type": "free",
        "price": 0,
        "features": ["OpenAPI Docs", "Zod Validation", "Type Safety", "Clean Structure"],
        "tech_stack": ["Hono", "TypeScript", "Zod", "OpenAPI"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Hono Starter",
        "slug": "hono-starter",
        "description": "Official Hono starter templates for multiple runtimes. 400+ stars on GitHub.",
        "long_description": "Official starter templates for Hono, the ultrafast web framework. Includes templates for Cloudflare Workers, Deno, Bun, Node.js, and more runtimes.",
        "git_repo_url": "https://github.com/honojs/starter.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f525",
        "tags": ["hono", "cloudflare", "deno", "bun", "edge"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Multi-Runtime", "Cloudflare Workers", "Deno", "Bun", "Edge"],
        "tech_stack": ["Hono", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── TanStack Start ────────────────────────────────────────
    {
        "name": "React TanStarter",
        "slug": "react-tanstarter",
        "description": "TanStack Start + React starter with modern tooling. 200+ stars on GitHub.",
        "long_description": "A starter template for TanStack Start with React, featuring file-based routing, server functions, and modern React patterns. Perfect for building type-safe full-stack React applications.",
        "git_repo_url": "https://github.com/dotnize/react-tanstarter.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\u269b",
        "tags": ["tanstack", "react", "typescript", "file-routing", "fullstack"],
        "pricing_type": "free",
        "price": 0,
        "features": ["File-based Routing", "Server Functions", "Type Safety"],
        "tech_stack": ["TanStack Start", "React", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "TanStack Boilerplate",
        "slug": "tanstack-boilerplate",
        "description": "Comprehensive TanStack Start boilerplate with auth and i18n. 200+ stars on GitHub.",
        "long_description": "A comprehensive boilerplate for TanStack Start featuring authentication, internationalization, dark mode, and a well-organized project structure with modern React patterns.",
        "git_repo_url": "https://github.com/nekochan0122/tanstack-boilerplate.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\u269b",
        "tags": ["tanstack", "react", "typescript", "auth", "i18n"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Authentication", "i18n", "Dark Mode", "Type Safety"],
        "tech_stack": ["TanStack Start", "React", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Rust ──────────────────────────────────────────────────
    {
        "name": "Loco",
        "slug": "loco",
        "description": "Rust on Rails — full-stack framework inspired by Rails. 5.8k+ stars on GitHub.",
        "long_description": "Loco is a Rust framework inspired by Ruby on Rails. Build full-stack web applications in Rust with MVC architecture, database migrations, background jobs, authentication, and more.",
        "git_repo_url": "https://github.com/loco-rs/loco.git",
        "default_branch": "master",
        "category": "backend",
        "icon": "\U0001f980",
        "tags": ["rust", "web-framework", "mvc", "rails-inspired", "backend"],
        "pricing_type": "free",
        "price": 0,
        "features": ["MVC Architecture", "Migrations", "Background Jobs", "Authentication"],
        "tech_stack": ["Rust", "Loco", "SeaORM"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Rust Axum Course",
        "slug": "rust-axum-course",
        "description": "Production-ready Rust Axum web API template. 1.2k+ stars on GitHub.",
        "long_description": "A comprehensive Rust web API project template using the Axum framework. Includes authentication, database layer, error handling, and a well-structured codebase for building production APIs.",
        "git_repo_url": "https://github.com/jeremychone-channel/rust-axum-course.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f980",
        "tags": ["rust", "axum", "web-api", "backend", "production"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Axum Framework", "Authentication", "Error Handling", "Database Layer"],
        "tech_stack": ["Rust", "Axum", "Tokio"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Elixir / Phoenix ──────────────────────────────────────
    {
        "name": "Petal Components",
        "slug": "petal-components",
        "description": "Phoenix LiveView component library with Tailwind CSS. 900+ stars on GitHub.",
        "long_description": "A beautiful set of HEEX components for Phoenix LiveView, styled with Tailwind CSS. Includes buttons, forms, modals, tables, and more — ready to use in any Phoenix project.",
        "git_repo_url": "https://github.com/petalframework/petal_components.git",
        "default_branch": "main",
        "category": "frontend",
        "icon": "\U0001f33a",
        "tags": ["elixir", "phoenix", "liveview", "tailwind", "components"],
        "pricing_type": "free",
        "price": 0,
        "features": ["LiveView Components", "Tailwind CSS", "Accessible", "Customizable"],
        "tech_stack": ["Elixir", "Phoenix", "LiveView", "Tailwind CSS"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Elixir Boilerplate",
        "slug": "elixir-boilerplate",
        "description": "Production-ready Elixir/Phoenix boilerplate by Mirego. 400+ stars on GitHub.",
        "long_description": "A production-ready Elixir/Phoenix boilerplate from Mirego featuring GraphQL, authentication, Docker, CI/CD, and a well-organized project structure following Elixir best practices.",
        "git_repo_url": "https://github.com/mirego/elixir-boilerplate.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f33a",
        "tags": ["elixir", "phoenix", "graphql", "docker", "boilerplate"],
        "pricing_type": "free",
        "price": 0,
        "features": ["GraphQL", "Authentication", "Docker", "CI/CD"],
        "tech_stack": ["Elixir", "Phoenix", "GraphQL", "Docker"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Turborepo ─────────────────────────────────────────────
    {
        "name": "SaaSfly",
        "slug": "saasfly",
        "description": "Next.js + Turborepo SaaS template with everything included. 1.5k+ stars on GitHub.",
        "long_description": "An all-in-one SaaS template built with Next.js and Turborepo. Includes authentication, Stripe payments, internationalization, blog, admin dashboard, and beautiful landing pages.",
        "git_repo_url": "https://github.com/saasfly/saasfly.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f680",
        "tags": ["turborepo", "nextjs", "saas", "stripe", "i18n", "monorepo"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Stripe Payments", "Authentication", "i18n", "Blog", "Admin Dashboard"],
        "tech_stack": ["Next.js", "Turborepo", "TypeScript", "Stripe", "Prisma"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Astro ─────────────────────────────────────────────────
    {
        "name": "Astroship",
        "slug": "astroship",
        "description": "Starter template for landing pages and websites with Astro. 2.5k+ stars on GitHub.",
        "long_description": "A beautiful starter template for landing pages, marketing sites, and websites built with Astro and Tailwind CSS. Features responsive design, SEO optimization, and fast page loads.",
        "git_repo_url": "https://github.com/surjithctly/astroship.git",
        "default_branch": "main",
        "category": "landing",
        "icon": "\U0001f680",
        "tags": ["astro", "landing-page", "tailwind", "seo", "static-site"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Responsive Design", "SEO Optimized", "Tailwind CSS", "Fast Loads"],
        "tech_stack": ["Astro", "Tailwind CSS"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    # ── Remix ─────────────────────────────────────────────────
    {
        "name": "Remix SaaS",
        "slug": "remix-saas",
        "description": "Production-ready Remix SaaS starter with Stripe and auth. 600+ stars on GitHub.",
        "long_description": "A lightweight, production-ready Remix SaaS template featuring Stripe subscriptions, authentication, role-based access, and a clean dashboard. Built for rapid SaaS development.",
        "git_repo_url": "https://github.com/dev-xo/remix-saas.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f4bf",
        "tags": ["remix", "saas", "stripe", "auth", "typescript"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Stripe Subscriptions", "Authentication", "RBAC", "Dashboard"],
        "tech_stack": ["Remix", "TypeScript", "Stripe", "Prisma"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Epic Stack",
        "slug": "epic-stack",
        "description": "Full-stack Remix starter by Kent C. Dodds. 5k+ stars on GitHub.",
        "long_description": "The Epic Stack by Kent C. Dodds — a production-ready Remix application with SQLite, Prisma, Fly.io deployment, comprehensive testing, authentication, and monitoring. The gold standard for Remix applications.",
        "git_repo_url": "https://github.com/epicweb-dev/epic-stack.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f4bf",
        "tags": ["remix", "fullstack", "prisma", "sqlite", "testing", "fly"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Prisma", "Authentication", "Testing", "Monitoring", "Fly.io Ready"],
        "tech_stack": ["Remix", "TypeScript", "Prisma", "SQLite", "Fly.io"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    # ── htmx ──────────────────────────────────────────────────
    {
        "name": "Go + htmx Examples",
        "slug": "go-htmx-examples",
        "description": "htmx examples with Go backend. 300+ stars on GitHub.",
        "long_description": "A collection of examples showing how to use htmx with a Go backend. Demonstrates progressive enhancement, partial page updates, and interactive UIs without heavy JavaScript frameworks.",
        "git_repo_url": "https://github.com/joerdav/go-htmx-examples.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f310",
        "tags": ["htmx", "go", "golang", "hypermedia", "examples"],
        "pricing_type": "free",
        "price": 0,
        "features": ["htmx Integration", "Go Backend", "Progressive Enhancement"],
        "tech_stack": ["Go", "htmx"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "htmx + Django",
        "slug": "htmx-django",
        "description": "Django project demonstrating htmx integration. 300+ stars on GitHub.",
        "long_description": "A Django project showcasing htmx integration for building dynamic web pages with minimal JavaScript. Demonstrates partial updates, infinite scroll, active search, and other htmx patterns.",
        "git_repo_url": "https://github.com/bugbytes-io/htmx-django.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f310",
        "tags": ["htmx", "django", "python", "hypermedia"],
        "pricing_type": "free",
        "price": 0,
        "features": ["htmx Integration", "Django", "Partial Updates", "Active Search"],
        "tech_stack": ["Django", "Python", "htmx"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Bun ───────────────────────────────────────────────────
    {
        "name": "Elysia",
        "slug": "elysia",
        "description": "Ergonomic framework for building backend servers with Bun. 10.5k+ stars on GitHub.",
        "long_description": "Elysia is an ergonomic web framework for building backend servers with Bun. Features end-to-end type safety, unified type system, and exceptional performance. Simple yet powerful API design.",
        "git_repo_url": "https://github.com/elysiajs/elysia.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f430",
        "tags": ["bun", "elysia", "typescript", "backend", "edge"],
        "pricing_type": "free",
        "price": 0,
        "features": ["End-to-End Type Safety", "Bun Runtime", "Fast Performance", "Simple API"],
        "tech_stack": ["Elysia", "Bun", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Deno Fresh ────────────────────────────────────────────
    {
        "name": "Deno Fresh",
        "slug": "deno-fresh",
        "description": "Next-gen web framework for Deno with island architecture. 12.5k+ stars on GitHub.",
        "long_description": "Fresh is a next generation web framework for Deno, featuring just-in-time rendering on the edge, island-based interactivity, zero runtime overhead, and no build step. Ships zero JavaScript to the client by default.",
        "git_repo_url": "https://github.com/denoland/fresh.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f34b",
        "tags": ["deno", "fresh", "edge", "islands", "typescript", "preact"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Island Architecture", "Edge Rendering", "Zero Build Step", "Preact"],
        "tech_stack": ["Deno", "Fresh", "Preact", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Kotlin / Ktor ─────────────────────────────────────────
    {
        "name": "Ktor Starter",
        "slug": "ktor-starter",
        "description": "Kotlin Ktor web application starter template. 100+ stars on GitHub.",
        "long_description": "A starter template for building web applications with Kotlin and the Ktor framework. Features authentication, database integration, dependency injection, and a clean project structure.",
        "git_repo_url": "https://github.com/niclas-timm/ktor-starter.git",
        "default_branch": "main",
        "category": "backend",
        "icon": "\U0001f4a0",
        "tags": ["kotlin", "ktor", "jvm", "backend", "web"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Authentication", "Database", "Dependency Injection", "Clean Structure"],
        "tech_stack": ["Kotlin", "Ktor"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── .NET / Blazor ─────────────────────────────────────────
    {
        "name": ".NET Starter Kit",
        "slug": "dotnet-starter-kit",
        "description": "Enterprise-grade .NET Web API + Blazor starter. 5.2k+ stars on GitHub.",
        "long_description": "An enterprise-grade .NET starter kit featuring a clean architecture Web API with Blazor frontend. Includes multi-tenancy, authentication, audit logging, CQRS with MediatR, and comprehensive documentation.",
        "git_repo_url": "https://github.com/fullstackhero/dotnet-starter-kit.git",
        "default_branch": "main",
        "category": "fullstack",
        "icon": "\U0001f4a0",
        "tags": ["dotnet", "blazor", "csharp", "clean-architecture", "multi-tenancy"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Multi-Tenancy", "CQRS", "Blazor Frontend", "Audit Logging"],
        "tech_stack": [".NET", "Blazor", "C#", "MediatR"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── SaaS ──────────────────────────────────────────────────
    {
        "name": "Open SaaS",
        "slug": "open-saas",
        "description": "Free, open-source SaaS starter with React and Node.js. 8.5k+ stars on GitHub.",
        "long_description": "Open SaaS is a free, open-source SaaS boilerplate built with Wasp, React, and Node.js. Includes authentication, Stripe payments, email integration, analytics, admin dashboard, blog, and landing page.",
        "git_repo_url": "https://github.com/wasp-lang/open-saas.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f4b0",
        "tags": ["saas", "react", "nodejs", "stripe", "wasp", "open-source"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Stripe Payments", "Auth", "Admin Dashboard", "Blog", "Analytics"],
        "tech_stack": ["Wasp", "React", "Node.js", "Stripe", "Prisma"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "SaaS Starter Kit (BoxyHQ)",
        "slug": "saas-starter-kit",
        "description": "Enterprise-ready SaaS starter kit with SSO and directory sync. 4k+ stars on GitHub.",
        "long_description": "An enterprise-ready SaaS starter kit from BoxyHQ featuring SAML SSO, Directory Sync, audit logs, webhooks, and team management. Built with Next.js, Prisma, and Tailwind CSS.",
        "git_repo_url": "https://github.com/boxyhq/saas-starter-kit.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f4b0",
        "tags": ["saas", "nextjs", "sso", "enterprise", "prisma", "tailwind"],
        "pricing_type": "free",
        "price": 0,
        "features": ["SAML SSO", "Directory Sync", "Audit Logs", "Webhooks", "Teams"],
        "tech_stack": ["Next.js", "Prisma", "Tailwind CSS", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "SaaS Boilerplate",
        "slug": "saas-boilerplate",
        "description": "Full-stack SaaS boilerplate with Next.js and Stripe. 3.5k+ stars on GitHub.",
        "long_description": "A production-ready SaaS boilerplate with Next.js, featuring Stripe subscriptions, authentication, landing pages, dashboard, and all the essential SaaS features out of the box.",
        "git_repo_url": "https://github.com/ixartz/SaaS-Boilerplate.git",
        "default_branch": "main",
        "category": "saas",
        "icon": "\U0001f4b0",
        "tags": ["saas", "nextjs", "stripe", "typescript", "boilerplate"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Stripe Subscriptions", "Authentication", "Dashboard", "Landing Page"],
        "tech_stack": ["Next.js", "TypeScript", "Stripe", "Tailwind CSS"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── AI / LLM ──────────────────────────────────────────────
    {
        "name": "Chatbot UI",
        "slug": "chatbot-ui",
        "description": "Open-source AI chatbot UI for multiple LLM providers. 28.8k+ stars on GitHub.",
        "long_description": "An open-source AI chatbot user interface supporting multiple LLM providers including OpenAI, Anthropic, Google, and more. Features conversation management, prompt templates, and a clean responsive design.",
        "git_repo_url": "https://github.com/mckaywrigley/chatbot-ui.git",
        "default_branch": "main",
        "category": "ai",
        "icon": "\U0001f916",
        "tags": ["ai", "chatbot", "llm", "openai", "anthropic", "ui"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Multi-Provider", "Conversation Management", "Prompt Templates", "Responsive"],
        "tech_stack": ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Dify",
        "slug": "dify",
        "description": "Open-source LLM app development platform. 56.8k+ stars on GitHub.",
        "long_description": "Dify is an open-source LLM app development platform that combines AI workflow, RAG pipeline, agent capabilities, model management, and observability features. Build production-ready AI applications visually.",
        "git_repo_url": "https://github.com/langgenius/dify.git",
        "default_branch": "main",
        "category": "ai",
        "icon": "\U0001f916",
        "tags": ["ai", "llm", "rag", "agents", "workflow", "platform"],
        "pricing_type": "free",
        "price": 0,
        "features": ["AI Workflow", "RAG Pipeline", "Agent System", "Model Management"],
        "tech_stack": ["Python", "React", "TypeScript", "PostgreSQL"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Vercel AI Chatbot",
        "slug": "vercel-ai-chatbot",
        "description": "Full-featured AI chatbot built with Next.js and Vercel AI SDK. 7.5k+ stars on GitHub.",
        "long_description": "A full-featured, hackable Next.js AI chatbot built by Vercel using the AI SDK. Features streaming responses, tool calling, multi-modal support, and authentication. Deployable with one click.",
        "git_repo_url": "https://github.com/vercel/ai-chatbot.git",
        "default_branch": "main",
        "category": "ai",
        "icon": "\U0001f916",
        "tags": ["ai", "chatbot", "nextjs", "vercel", "ai-sdk", "streaming"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Streaming", "Tool Calling", "Multi-Modal", "Authentication"],
        "tech_stack": ["Next.js", "Vercel AI SDK", "TypeScript", "Tailwind CSS"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── Admin ─────────────────────────────────────────────────
    {
        "name": "React Admin",
        "slug": "react-admin",
        "description": "Frontend framework for building admin applications. 25.3k+ stars on GitHub.",
        "long_description": "React-admin is a frontend framework for building data-driven admin applications with React. Features CRUD views, data providers, authentication, theming, and a rich library of input components.",
        "git_repo_url": "https://github.com/marmelab/react-admin.git",
        "default_branch": "master",
        "category": "admin",
        "icon": "\U0001f4ca",
        "tags": ["react", "admin", "dashboard", "crud", "data-driven"],
        "pricing_type": "free",
        "price": 0,
        "features": ["CRUD Views", "Data Providers", "Authentication", "Theming"],
        "tech_stack": ["React", "TypeScript", "Material UI"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Refine",
        "slug": "refine",
        "description": "React framework for building internal tools and admin panels. 29.5k+ stars on GitHub.",
        "long_description": "Refine is a React meta-framework for building CRUD-heavy web applications like admin panels, dashboards, and internal tools. Supports any custom design, REST/GraphQL backends, and popular UI frameworks.",
        "git_repo_url": "https://github.com/refinedev/refine.git",
        "default_branch": "master",
        "category": "admin",
        "icon": "\U0001f4ca",
        "tags": ["react", "admin", "internal-tools", "crud", "refine"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Any UI Framework", "REST/GraphQL", "Authentication", "Access Control"],
        "tech_stack": ["React", "TypeScript"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    # ── Landing Page ──────────────────────────────────────────
    {
        "name": "Open React Template",
        "slug": "open-react-template",
        "description": "Free React landing page template by Cruip. 1.7k+ stars on GitHub.",
        "long_description": "A free, open-source React landing page template designed by Cruip. Features beautiful design, smooth animations, responsive layout, and easy customization with Tailwind CSS.",
        "git_repo_url": "https://github.com/cruip/open-react-template.git",
        "default_branch": "master",
        "category": "landing",
        "icon": "\U0001f3a8",
        "tags": ["react", "landing-page", "tailwind", "template", "free"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Beautiful Design", "Animations", "Responsive", "Tailwind CSS"],
        "tech_stack": ["React", "Tailwind CSS", "TypeScript"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    {
        "name": "Taxonomy",
        "slug": "taxonomy",
        "description": "Next.js app built with Radix UI and Tailwind CSS. 18.5k+ stars on GitHub.",
        "long_description": "An open-source application built using Next.js 13, showcasing the new features like Server Components, app directory, and more. Features authentication, subscriptions, and a beautiful UI with Radix and Tailwind.",
        "git_repo_url": "https://github.com/shadcn-ui/taxonomy.git",
        "default_branch": "main",
        "category": "landing",
        "icon": "\U0001f3a8",
        "tags": ["nextjs", "radix-ui", "tailwind", "shadcn", "landing"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Server Components", "Auth", "Subscriptions", "Radix UI"],
        "tech_stack": ["Next.js", "Radix UI", "Tailwind CSS", "TypeScript"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    # ── CLI (Go) ──────────────────────────────────────────────
    {
        "name": "Cobra",
        "slug": "cobra",
        "description": "Go library for creating powerful CLI applications. 38.8k+ stars on GitHub.",
        "long_description": "Cobra is a library for creating powerful modern CLI applications in Go. Used by Kubernetes, Hugo, and many other popular tools. Features auto-generated help, shell completions, and intelligent suggestions.",
        "git_repo_url": "https://github.com/spf13/cobra.git",
        "default_branch": "main",
        "category": "cli",
        "icon": "\U0001f4bb",
        "tags": ["go", "cli", "cobra", "command-line", "terminal"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Auto Help", "Shell Completions", "Suggestions", "Nested Commands"],
        "tech_stack": ["Go", "Cobra"],
        "is_featured": True,
        "is_active": True,
        "visibility": "public",
    },
    # ── CLI (Node) ────────────────────────────────────────────
    {
        "name": "oclif",
        "slug": "oclif",
        "description": "Framework for building CLIs in Node.js. 9.1k+ stars on GitHub.",
        "long_description": "oclif is a framework for building command-line tools in Node.js. Created by Heroku/Salesforce, it features plugin support, auto-generated docs, TypeScript support, and testing utilities.",
        "git_repo_url": "https://github.com/oclif/oclif.git",
        "default_branch": "main",
        "category": "cli",
        "icon": "\U0001f4bb",
        "tags": ["nodejs", "cli", "oclif", "typescript", "command-line"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Plugin System", "Auto Docs", "TypeScript", "Testing Utils"],
        "tech_stack": ["Node.js", "TypeScript", "oclif"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
    # ── CLI (Rust) ────────────────────────────────────────────
    {
        "name": "clap",
        "slug": "clap",
        "description": "Full-featured CLI argument parser for Rust. 14.5k+ stars on GitHub.",
        "long_description": "clap is a full-featured, fast Command Line Argument Parser for Rust. Features derive macros, auto-generated help, shell completions, and comprehensive validation. The most popular CLI library in the Rust ecosystem.",
        "git_repo_url": "https://github.com/clap-rs/clap.git",
        "default_branch": "master",
        "category": "cli",
        "icon": "\U0001f4bb",
        "tags": ["rust", "cli", "clap", "argument-parser", "command-line"],
        "pricing_type": "free",
        "price": 0,
        "features": ["Derive Macros", "Auto Help", "Shell Completions", "Validation"],
        "tech_stack": ["Rust", "clap"],
        "is_featured": False,
        "is_active": True,
        "visibility": "public",
    },
]


async def get_or_create_community_account(db: AsyncSession) -> User:
    """Get or create the shared 'Open Source Community' user account."""
    result = await db.execute(
        select(User).where(User.email == COMMUNITY_ACCOUNT["email"])
    )
    user = result.scalar_one_or_none()

    if user:
        return user

    user = User(
        id=str(uuid.uuid4()),
        email=COMMUNITY_ACCOUNT["email"],
        username=COMMUNITY_ACCOUNT["username"],
        slug=COMMUNITY_ACCOUNT["slug"],
        name=COMMUNITY_ACCOUNT["display_name"],
        hashed_password="!disabled",
    )
    db.add(user)
    await db.flush()
    logger.info("Created community account: %s", COMMUNITY_ACCOUNT["email"])
    return user


async def seed_community_bases(db: AsyncSession) -> int:
    """Seed community marketplace bases. Upserts by slug.

    Returns:
        Number of newly created bases.
    """
    community_user = await get_or_create_community_account(db)
    created = 0
    updated = 0

    for base_data in COMMUNITY_BASES:
        result = await db.execute(
            select(MarketplaceBase).where(MarketplaceBase.slug == base_data["slug"])
        )
        existing = result.scalar_one_or_none()

        if existing:
            for key, value in base_data.items():
                if key != "slug":
                    setattr(existing, key, value)
            if not existing.created_by_user_id:
                existing.created_by_user_id = community_user.id
            updated += 1
            logger.info("Updated community base: %s", base_data["slug"])
        else:
            base = MarketplaceBase(
                **base_data,
                created_by_user_id=community_user.id,
            )
            db.add(base)
            created += 1
            logger.info("Created community base: %s", base_data["name"])

    await db.commit()

    logger.info(
        "Community bases: %d created, %d updated",
        created,
        updated,
    )
    return created
