apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - rbac/controller-rbac.yaml
  - rbac/node-rbac.yaml
  - manifests/csi-driver.yaml
  - manifests/storage-class.yaml
  - manifests/snapshot-class.yaml
  - manifests/controller.yaml
  - manifests/node.yaml
  - manifests/node-service.yaml
  - manifests/network-policy.yaml
  - manifests/image-precache.yaml
